# Problem 2:

# Problem Statement

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibonacci_seq(x, y, z):
    """

    :param x: Current Fibonacci sequence number
    :param y: Next Fibonacci number in the sequence
    :param z: Maximum value for fibonacci number
    :return sum: The sum of even-valued terms between x and y

    """
    ans = 0
    while x <= z:
        if x % 2 == 0:
            ans += x
        x, y = y, x + y

    return ans


if __name__ == "__main__":
    print(even_fibonacci_seq(1, 2, 4000000))
    ## answer is 4613732
